
<!-- This modal is used when user clicks on an item in the table generated by Inventory.php
     The user can click 'Borrow', and is sent to Borrow.php.
     Or, they can click on 'Page for this item' link, and be sent to generatedItemPage.php.
-->

<div style="display: none;">
    <!-- Button to request data from server. -->
    <form action="Borrow" method="GET" id="formSenDItemID">
        <input id="itemIdUserInput" type="text" name="itemID" style="display: none;" value="">
    </form>
    <button type="submit" form="formSenDItemID" id="borrowButton"><h2>Borrow!</h2></button>
</div>

<script>
    /* Gets itemID from clicked element in result table, used in inventory.php */
    function clickOnItem(e) {
        $("tr").click(function(event) {
            //itemID from clicked <tr>
            var itemID = $(this).closest('tr').find('td:first-child').text();


            //Place itemID where user clicked into modal
            document.querySelector('#itemIdUserInput').setAttribute('value', itemID);

            if (itemID == undefined || itemID == '' || itemID === 'No Match') return; //Can't select title of item table.
            borrowModalSweetAlert(itemID)
        })
    }


    /**
     Promt asking user if they want to borrow the selected item.
     If yes --> User is sent to Borrow.php, and the itemID is auto filled.
     If no  --> Promt closes.
     */
    function borrowModalSweetAlert(itemID) {
        Swal.fire({
            icon: 'question',
            title: 'Do you want to borrow '+itemID+'?',
            showDenyButton: true,
            denyButtonText: `No`,
            confirmButtonText: `Yes`,
            confirmButtonColor: 'green',
            html: '<p><a id="itemIDForUserGeneratedItemPage" href="Equipment/'+itemID+'">Click here for more details about this instrument</a></p>',
        }).then((result) => {
            if (result.isConfirmed) {
                //Send to borrow page.
                document.querySelector('#borrowButton').click(); //Click the button activating the 'formSenDItemID' form.
            }
        })
    }
</script>
