
<!-- This modal is used when user clicks on an item in the table generated by Inventory.php
     The user can click 'Borrow', and is sent to Borrow.php.
     Or, they can click on 'Page for this item' link, and be sent to generatedItemPage.php.
-->
<script>
    /**
     Promt asking user if they want to raplce image.
     */
    function updateEquipmentImage() {
        Swal.fire({
            icon: 'question',
            title: 'Replace image for' + " {{ "$equipmentID" }}" + '?',
            showDenyButton: true,
            denyButtonText: `No`,
            confirmButtonText: `Yes`,
            confirmButtonColor: 'green',
            html: "<form name='updateImageForm' id='updateImageForm' action='{{ url("/Equipment/$equipmentID/updateImage") }}' method='POST' enctype='multipart/form-data'>"
                +'@csrf'+
                "<div class='col'>"+
                    "<div class='input-group mb-3 w-50 mx-auto'>"+
                            "<label class='form-label ' for='imgFile'></label><br>"+
                            "<input class='form-control' name='imgFile' id='imgFile' type='file'/>"+
                    "</div>"+
                    "<div class='form-check form-check-inline'>"+
                        "<input class='form-check-input' type='radio' name='imageFormatting' id='cut' value='cut' checked>"+
                        "<label class='form-check-label' for='cut'> Cut</label>" +
                    "</div>"+
                    "<div class='form-check form-check-inline'>"+
                        "<input class='form-check-input' type='radio' name='imageFormatting' id='resize' value='resize'>"+
                        "<label class='form-check-label' for='resize'> Resize</label>"+
                    "</div>"+
                    "<input name='equipmentID' style='display:none;' value="+"{{$equipmentID}}"+">"+
                    "</div>" +
                "</form>",
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById("updateImageForm").submit(); //Click the button activating the 'updateImageForm' form.
            }
        })
    }
</script>

<?php
/* Old version of form.
    html: "<form name='updateImageForm' id='updateImageForm' action='{{ url("/Equipment/$equipmentID/updateImage") }}' method='POST' enctype='multipart/form-data'> " + '@csrf' + " <input name='equipmentID' style='display:none;' value="+"{{$equipmentID}}"+"> <label for='imgFile'>Upload new image</label> <br><input name='imgFile' id='imgFile' type='file'/></form>"
 */
?>
