version: "3.8"

services: 
    db:
        image: mysql:8.0
        ports:
            - "33061:3306"
        volumes: 
            - db-data:/var/lib/mysql
        environment:
            #MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 
            MYSQL_PASSWORD: 
            MYSQL_DATABASE: 'testcenterequipmentdatabase'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: unless-stopped

    app:
        build: .
        entrypoint: /usr/local/bin/docker-php-entrypoint
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
        container_name: app-laerdal-database
        volumes:
            - ./src:/var/www/app
        environment: 
            APP_ENV: local
            APP_KEY: base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
            APP_DEBUG: true
            DB_CONNECTION: mysql
            DB_HOST: db ## same as the database service name
            DB_PORT: 3306
            DB_DATABASE: 'testcenterequipmentdatabase'
            DB_USERNAME: 'root'
            DB_PASSWORD: 
        restart: unless-stopped
        ports: 
            - 8000:80
        depends_on:
            - db

volumes:
    db-data:
        driver: local
    app-data:
        driver: local